namespace HaWeb.Settings;

public static class General {
    // Classes generated by parsing the XML:
    public const string XMLFILEPATH = @"Hamann.xml";
    public const bool NORMALIZEWHITESPACE = true;
    public static (int, int) AVAILABLEYEARRANGE = (1751, 1788);
    public static string[] AVAILABLEVOLUMES = { };
}