name: hamann-ausgabe
services:
  hamannservice:
    build: .
    expose:
      - "5000"
    volumes:
      - hamann_data:/app/data
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_ENVIRONMENT=Production
      - FileStoragePath=/app/data
      - RepositoryBranch=Release
      - RepositoryURL=https://github.com/Theodor-Springmann-Stiftung/hamann-xml
    restart: unless-stopped
    networks:
      - caddynet

volumes:
  hamann_data:
    external: true

networks:
  caddynet:
    external: true
